//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCRental_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class K21T3_Team1_PPC3129Entities : DbContext
    {
        public K21T3_Team1_PPC3129Entities()
            : base("name=K21T3_Team1_PPC3129Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DISTRICT> DISTRICT { get; set; }
        public DbSet<FEATURE> FEATURE { get; set; }
        public DbSet<PROJECT_STATUS> PROJECT_STATUS { get; set; }
        public DbSet<PROPERTY> PROPERTY { get; set; }
        public DbSet<PROPERTY_FEATURE> PROPERTY_FEATURE { get; set; }
        public DbSet<PROPERTY_TYPE> PROPERTY_TYPE { get; set; }
        public DbSet<STREET> STREET { get; set; }
        public DbSet<USER> USER { get; set; }
        public DbSet<WARD> WARD { get; set; }
    }
}
