//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCRental_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class USER
    {
        public USER()
        {
            this.PROPERTY = new HashSet<PROPERTY>();
            this.PROPERTY1 = new HashSet<PROPERTY>();
        }
    
        public int ID { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        public string FullName { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        [StringLength(15)]
        public string Phone { get; set; }

        [Required]
        public string Address { get; set; }

        public string Role { get; set; }

        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<PROPERTY> PROPERTY { get; set; }
        public virtual ICollection<PROPERTY> PROPERTY1 { get; set; }
    }
}
